import type { BentoItemData } from "./types";

const YOUTUBE_LINK = "https://youtube.com/@evoloper0";

export const YOUTUBE_ITEMS: BentoItemData[] = [
  {
    id: "youtube-subs",
    icon: "youtube",
    link: YOUTUBE_LINK,
    label: "Subscribe",
    sublabel: "Go to my Youtube channel",
  },
  {
    id: "youtube-1",
    spanX: 2,
    spanY: 1,
    icon: "youtube",
    link: YOUTUBE_LINK,
    label: "@evoloper YouTube kanalıma git",
    image: "/youtube/77t-FTb8D9I-SD.jpg",
  },
  {
    id: "youtube-comment",
    icon: "youtube_comment",
    link: YOUTUBE_LINK,
    label: "Elinize emeğinize sağlık ancak bu kadar güzel anlatılırdı 👏🏻👏🏻",
    sublabel: "@Ozyeyo",
  },
  {
    id: "youtube-2",
    spanX: 2,
    spanY: 1,
    icon: "youtube",
    link: YOUTUBE_LINK,
    label: "@evoloper YouTube kanalıma git",
    image: "/youtube/aaLbmi7sXmg-SD.jpg",
  },
  {
    id: "youtube-3",
    spanX: 2,
    spanY: 1,
    icon: "youtube",
    link: YOUTUBE_LINK,
    label: "@evoloper YouTube kanalıma git",
    image: "/youtube/aEr9WDp5z5g-SD.jpg",
  },
  {
    id: "youtube-comment-2",
    icon: "youtube_comment",
    link: YOUTUBE_LINK,
    label: "Yarın almayı planlıyorum, iyi ki izledim tüm soru işaretlerim gitti emeğinize sağlık❤",
    sublabel: "@SimülasyonGamer",
  },
  {
    id: "youtube-4",
    spanX: 2,
    spanY: 1,
    icon: "youtube",
    link: YOUTUBE_LINK,
    label: "@evoloper YouTube kanalıma git",
    image: "/youtube/BdRjQGJgW38-SD.jpg",
    stat: "100+",
  },
  {
    id: "youtube-comment-3",
    icon: "youtube_comment",
    link: YOUTUBE_LINK,
    label: "Size çok teşekkür ederim iki saat her yerden aradım nasıl kullanır diye siz karşıma çıktınız çok güzel anlattınız teşekkür ederim",
    sublabel: "@ElifKaban-d2x5e",
  },
  {
    id: "youtube-5",
    spanX: 2,
    spanY: 1,
    icon: "youtube",
    link: YOUTUBE_LINK,
    label: "@evoloper YouTube kanalıma git",
    image: "/youtube/cZyu_4_wFO8-SD.jpg",
    stat: "100+",
  },
  {
    id: "youtube-subs-count",
    icon: "subscribers",
    link: YOUTUBE_LINK,
    label: "Subscriber",
    stat: "1.5k+",
  },
  {
    id: "youtube-7",
    icon: "youtube",
    link: YOUTUBE_LINK,
    label: "@evoloper YouTube kanalıma git",
    image: "/youtube/Mavl7QQgMu4-SD.jpg",
    stat: "100+",
  },
  {
    id: "youtube-view",
    icon: "views",
    link: YOUTUBE_LINK,
    label: "Views",
    stat: "157.8K+",
  },
  {
    id: "youtube-6",
    spanX: 2,
    spanY: 1,
    icon: "youtube",
    link: YOUTUBE_LINK,
    label: "@evoloper YouTube kanalıma git",
    image: "/youtube/iCaWleQqaX0-SD.jpg",
    stat: "100+",
  },
  {
    id: "youtube-hours",
    icon: "watch_time",
    link: YOUTUBE_LINK,
    label: "Watch time (hours)",
    stat: "4.7K+",
  },
  {
    id: "youtube-comment-4",
    icon: "youtube_comment",
    link: YOUTUBE_LINK,
    label: "Üstad selamlar. Öncelikle video için teşekkürler. Çok açıklayıcı ve faydalı bir video olmuş eline sağlık. Ailemle birlikte kamp yapmaya başlayacağız...",
    sublabel: "@shnkamp",
  },
  {
    id: "youtube-comment-5",
    icon: "youtube_comment",
    link: YOUTUBE_LINK,
    label: "@evoloper0 hay Allah razı olsun abicim ya çok teşekkür ederim ❤",
    sublabel: "@TrSavunma",
  },
  {
    id: "youtube-comment-6",
    icon: "youtube_comment",
    link: YOUTUBE_LINK,
    label: "Abi Allah senden razı olsun kaç saattir uğraşıyorum çözemedim sen çıktın karşıma 10 dk da kurdum çok teşekkür ederim",
    sublabel: "@badenes5603",
  },
  {
    id: "youtube-comment-7",
    icon: "youtube_comment",
    link: YOUTUBE_LINK,
    label: "izlediğim en garip araba tanıtımı videosu. gülem mi izleyem mi karar veremedim xd ikna ettiniz beni chr ye",
    sublabel: "@kenybadi",
  },
];
